
@startuml

interface Access [[#Access]] {
  phoneNumber: string [[#phoneNumber]]
  price: number [[#price]]
  dateTime: string [[#dateTime]]
}

class Bill [[#Bill]] #wheat {
  month: string [[#month]]
  contract: Contract [[#contract]]
  accesses: Access[] [[#accesses]]
  paymentState: PaymentState [[#paymentState]]
}

interface BillsService [[#BillsService]] {
  getBills(): Bill[]
  getBill(month: string): Bill
}

interface CallAccess [[#CallAccess]] {
  duration: string [[#duration]]
}

interface Contract [[#Contract]] {
  id: number [[#id]]
  customer: Customer [[#customer]]
}

interface Customer [[#Customer]] {
  email: string [[#email]]
  contracts: Contract[] [[#contracts]]
}

enum PaymentState [[#PaymentState]] {
  WAITING [[#WAITING]]
  DONE [[#DONE]]
}

interface SmsAccess [[#SmsAccess]]

Access <|- CallAccess
Access <|- SmsAccess
Bill --> "*" Access: accesses
Bill --> Contract: contract
Bill --> PaymentState: paymentState
BillsService -- Bill: use
Contract --> Customer: customer
Customer --> "*" Contract: contracts

@enduml
