@startuml
!pragma layout smetana

header
hide BillingService fields
endheader

abstract class "Access" [[glossary.html#glossaryid-400{Access}]] {
  phoneNumber : String [[glossary.html#glossaryid-401{phoneNumber}]]
  price : BigDecimal [[glossary.html#glossaryid-402{price}]]
  dateTime : ZonedDateTime [[glossary.html#glossaryid-403{dateTime}]]
}

class "Bill" [[glossary.html#glossaryid-100{Bill}]] #pink {
  month : YearMonth [[glossary.html#glossaryid-101{month}]]
  contract : Contract [[glossary.html#glossaryid-102{contract}]]
  accesses : Set<Access> [[glossary.html#glossaryid-103{accesses}]]
  customerInformed : boolean [[glossary.html#glossaryid-Bill_customerInformed{customerInformed}]]
}

interface "BillRepository" [[glossary.html#glossaryid-BillRepository{BillRepository}]] {
  add(Bill) : Bill
  clear()
  get(YearMonth) : Optional<Bill>
  retreiveLastBill() : Optional<Bill>
}

class "BillingService" [[glossary.html#glossaryid-BillingService{BillingService}]] {
  repository : BillRepository [[glossary.html#glossaryid-BillingService_repository{repository}]]
  getBill(String) : Optional<Bill>
}

class "CallAccess" [[glossary.html#glossaryid-500{CallAccess}]] {
  duration : Duration [[glossary.html#glossaryid-501{duration}]]
}

class "Contract" [[glossary.html#glossaryid-200{Contract}]] {
  id : String [[glossary.html#glossaryid-201{id}]]
  customer : Customer [[glossary.html#glossaryid-202{customer}]]
  effectDate : LocalDate [[glossary.html#glossaryid-203{effectDate}]]
}

class "Customer" [[glossary.html#glossaryid-300{Customer}]] {
  name : String [[glossary.html#glossaryid-301{name}]]
  contracts : Set<Contract> [[glossary.html#glossaryid-Customer_contracts{contracts}]]
}

class "ListBillRepository" [[glossary.html#glossaryid-ListBillRepository{ListBillRepository}]]

class "SmsAccess" [[glossary.html#glossaryid-600{SmsAccess}]]

"Access" <|-- "CallAccess"
"Access" <|-- "SmsAccess"
"Bill" --> "*" "Access" : accesses
"Bill" --> "Contract" : contract
"BillRepository" --> "Bill" : use
"BillRepository" <|-- "ListBillRepository"
"BillingService" --> "Bill" : use
"BillingService" --> "BillRepository" : repository
"Contract" "*" <-> "Customer" : customer/contracts
footer

endfooter


@enduml
