#!/bin/bash

# Script bash de déploiement des artefact dans maven centrale
#
# suivant différentes conditions ce sera une version realease ou snapshot
# du projet livingdoc-annotations et/ou du projet livingdoc-manven-plugin

if [ "$TRAVIS_PULL_REQUEST" != "false" ] || [ "$TRAVIS_BRANCH" != "master" ]; then
    echo "no release on PR or non master branch"
    exit 0
fi

echo "running deployment script..."

fixReleaseVersion() {
    echo "set $1 to release version"
    if ! mvn -f $1/pom.xml -q build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion} versions:commit; then
        echo "set release version failed"
        exit 1
    fi
}

setNextDevVersion() {
    echo "set $1 to next development version"
    if ! mvn -f $1/pom.xml -q build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.nextMinorVersion}-SNAPSHOT versions:commit; then
        echo "set next development version failed"
        exit 1
    fi
}

tag() {
    local project=$1
    echo "reading $project version..."
    local version=`cd $project && mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | sed -n -e '/^\[.*\]/ !{ /^[0-9]/ { p; q } }'`
    local tag="release/$project/v$version"
    echo "create git tag $tag"
    git tag "$tag" -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
}

deploy() {
    echo "deploying version $1 to maven centrale..."
    if ! mvn -f $1/pom.xml deploy --settings $GPG_DIR/settings.xml -Prelease -DskipTests=true -B; then
        echo "maven deploy failed"
        exit 1
    fi
}

hasChange() {
    local check_path=$1'/'

    echo "Checking changes since ${TRAVIS_COMMIT_RANGE} against ${check_path}"
    GITDIFF=$(git diff --name-only ${TRAVIS_COMMIT_RANGE} | grep ${check_path} | tr -d '[:space:]')
    if [ "$GITDIFF" == "" ]; then
        echo "No code changes, skipped"
        return 0
    fi
    echo "Code changes"
    return 1
}

hasForceMessage() {
    if [[ "$TRAVIS_COMMIT_MESSAGE" =~ "force release $1" ]];then
        echo 1
    else
        echo 0
    fi
}

needRelease() {
    if [ `hasForceMessage $1` = 1 ]; then
        echo "Force $1 release"
        return 1
    fi

    hasChange $1
    if [ $? = 1 ]; then
        return 1
    fi
    return 0
}

needRelease livingdoc-maven-plugin
MAKE_RELEASE_PLUGIN=$?
needRelease livingdoc-annotations
MAKE_RELEASE_ANNOTATION=$?

if [ $MAKE_RELEASE_PLUGIN = 1 ]; then
    fixReleaseVersion livingdoc-maven-plugin
fi

if [ $MAKE_RELEASE_ANNOTATION = 1 ]; then
    fixReleaseVersion livingdoc-annotations
fi

# deploy release or snapshot
deploy livingdoc-annotations
deploy livingdoc-maven-plugin

if [ $MAKE_RELEASE_PLUGIN = 1 ] || [ $MAKE_RELEASE_ANNOTATION = 1 ]; then
    # reconnect master to origin
    git checkout master

    git config user.name "Travis CI"
    git config user.email "travis-ci@ifocusit.ch"

    NEXT_VERSION=''
    if [ $MAKE_RELEASE_PLUGIN = 1 ]; then
        tag livingdoc-maven-plugin
        setNextDevVersion livingdoc-maven-plugin
        version=`cd livingdoc-maven-plugin && mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | sed -n -e '/^\[.*\]/ !{ /^[0-9]/ { p; q } }'`
        NEXT_VERSION+=" livingdoc-maven-plugin: $version"
    fi
    if [ $MAKE_RELEASE_ANNOTATION = 1 ]; then
        tag livingdoc-annotations
        setNextDevVersion livingdoc-annotations
        version=`cd livingdoc-annotations && mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | sed -n -e '/^\[.*\]/ !{ /^[0-9]/ { p; q } }'`
        NEXT_VERSION+=" livingdoc-annotations: $version"
    fi

    echo "next development version will be $NEXT_VERSION"

    # Commit the "changes", i.e. the new version.
    git add -A .
    git commit -m "set next development version to $NEXT_VERSION"

    echo "pushing new development version..."
    git push "https://$GITHUB_TOKEN@github.com/$TRAVIS_REPO_SLUG.git" --follow-tags

    echo "release done, tag pushed, next development version setted"
fi
