#!/bin/bash

function deployIfCodeChanges {
    CHECK_PATH=$1'/'
    if [ "$TRAVIS_BRANCH" = 'master' ] && [ "$TRAVIS_PULL_REQUEST" = 'false' ]; then
        # This is PR
        echo "Checking changes since ${TRAVIS_COMMIT_RANGE} against ${CHECK_PATH}"
        GITDIFF=`git diff --name-only ${TRAVIS_COMMIT_RANGE} | grep ${CHECK_PATH} | tr -d '[:space:]'`
        if [ "$GITDIFF" == "" ]; then
            echo "No code changes, skipped script"
            exit 1
        fi
        echo "$1 code change, deploy version"
        # npm run deploy
        echo "ready for deployment"
    fi
}

if [ "${TRAVIS_COMMIT_MESSAGE}" =~ npm\ release ] && [ "$TRAVIS_BRANCH" = 'master' ] && [ "$TRAVIS_PULL_REQUEST" = 'false' ]; then 
    deployIfCodeChanges livingdoc-typescript-plugin
fi