#!/bin/bash

project=$1

if [ "$project" != "livingdoc-maven-plugin" ] || [ "$project" != "livingdoc-annotations" ]; then
  echo "Bad project name !"
  exit 1
fi

if [ "$TRAVIS_TOKEN" = "" ]; then
  echo "no TRAVIS_TOKEN defined !"
  exit 1
fi

body="{
  "request": {
    "branch": "master",
    "message": "force release $project"
  }
}"

curl -s -X POST \
-H "Content-Type: application/json" \
-H "Accept: application/json" \
-H "Travis-API-Version: 3" \
-H "Authorization: token $TRAVIS_TOKEN" \
-d "$body" \
https://api.travis-ci.org/jboz%2Fliving-documentation/requests
