#!/bin/bash

#npm run build:ci

PROJECT_VERSION="$(node -p "require('./package.json').version")"
echo "PROJECT_VERSION=$PROJECT_VERSION"
# NPM_PACKAGE_VERSION="$(npm view livingdoc-typescript-plugin version)"
# echo "NPM_PACKAGE_VERSION=$NPM_PACKAGE_VERSION"

# # check that the version was upgrade with 'npm version xxx' command
# if [ "$TRAVIS_PULL_REQUEST" != "false" ] && [ "$TRAVIS_BRANCH" == "master" ] && [ "$PROJECT_VERSION" == "$NPM_PACKAGE_VERSION" ]; then
#     echo -e '\033[0;31mPackage version must be higher than the current one.'
#     exit 1
# fi

#if [ "$TRAVIS_BRANCH" = 'master' ] && [ "$TRAVIS_PULL_REQUEST" = 'false' ]; then
# tag git repository
git config user.name "Travis CI"
git config user.email "travis-ci@ifocusit.ch"
GIT_TAG="release/typescript-plugin/v$PROJECT_VERSION"
echo "create git tag $GIT_TAG"
git tag "$GIT_TAG" -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"

git config --global push.followTags true # push commit and tag
# as git tagged, npm publish will be launch
f#i
