package ch.ifocusit.livingdoc.example.cargo.model;

import ch.ifocusit.livingdoc.annotations.UbiquitousLanguage;
import ch.ifocusit.livingdoc.example.shared.ValueObject;
import org.apache.commons.lang.Validate;

/**
 * Uniquely identifies a particular cargo. Automatically generated by the application.
 */
@UbiquitousLanguage
public final class TrackingId implements ValueObject<TrackingId> {

    @UbiquitousLanguage
    private String id;

    /**
     * Constructor.
     *
     * @param id Id string.
     */
    public TrackingId(final String id) {
        Validate.notNull(id);
        this.id = id;
    }

    TrackingId() {
        // Needed by Hibernate
    }

    /**
     * @return String representation of this tracking id.
     */
    public String idString() {
        return id;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        TrackingId other = (TrackingId) o;

        return sameValueAs(other);
    }

    @Override
    public int hashCode() {
        return id.hashCode();
    }

    @Override
    public boolean sameValueAs(TrackingId other) {
        return other != null && this.id.equals(other.id);
    }

    @Override
    public String toString() {
        return id;
    }
}
