### get page content
GET https://cwiki.ifocusit.ch/rest/api/content
    ?spaceKey=DOCPROD
    &title=zz - Domain diagram with link - manual upload
    &expand=body.storage
Authorization: Basic anVsaWVuOkAxbW9yZVQhbWU=

### add page
POST https://cwiki.ifocusit.ch/rest/api/content
Accept: application/json
Content-Type: application/json;charset=utf-8
Authorization: Basic anVsaWVuOkAxbW9yZVQhbWU=

{
  "type": "page",
  "ancestors": [
    {
      "id": 98369
    }
  ],
  "space": {
    "key": "DOCPROD"
  },
  "title": "zz - Domain diagram with link - manual upload",
  "body": {
    "storage": {
      "value": "<p>This is a new page</p>",
      "representation": "storage"
    }
  }
}

### update page
PUT https://cwiki.ifocusit.ch/rest/api/content/6258696
Accept: application/json
Content-Type: application/json;charset=utf-8
Authorization: Basic anVsaWVuOkAxbW9yZVQhbWU=

{
  "type": "page",
  "ancestors": [
    {
      "id": 98369
    }
  ],
  "space": {
    "key": "DOCPROD"
  },
  "title": "zz - Domain diagram with link - manual upload",
  "body": {
    "storage": {
      "value": "<ac:structured-macro ac:name='plantuml' ac:schema-version='1' ac:macro-id='c93806da-006e-4cfa-9d67-bfe2f255e2fb'><ac:parameter ac:name='atlassian-macro-output-type'>INLINE</ac:parameter><ac:plain-text-body><![CDATA[!include ^diagram.plantuml]]></ac:plain-text-body></ac:structured-macro><ri:attachment ri:filename=\"diagram.plantuml\"></ri:attachment>",
               "<ac:structured-macro ac:name='plantuml' ac:schema-version='1' ac:macro-id='c93806da-006e-4cfa-9d67-bfe2f255e2fb'><ac:parameter ac:name='atlassian-macro-output-type'>INLINE</ac:parameter><ac:plain-text-body><![CDATA[!include ^diagram.plantuml]></ac:plain-text-body></ac:structured-macro><ri:attachment ri:filename="diagram.plantuml"></ri:attachment>"
      "representation": "storage"
    }
  },
  "version": {
    "number": 22
  }
}

// "value": "<ac:task-list><ac:task><ac:task-id>1</ac:task-id><ac:task-status>incomplete</ac:task-status><ac:task-body><ac:link><ri:user ri:username='julien' /></ac:link>do something</ac:task-body></ac:task></ac:task-list>",

### upload attachment
POST https://cwiki.ifocusit.ch/rest/api/content/6258696/child/attachment
Accept: */*
Authorization: Basic anVsaWVuOkAxbW9yZVQhbWU=
X-Atlassian-Token: no-check
Content-Type: multipart/form-data; boundary=------------------------attachment-content

--------------------------attachment-content
Content-Disposition: form-data; name="file"; filename="diagram.plantuml"

< ddd/target/diagram.plantuml
--------------------------attachment-content
Content-Disposition: form-data; name="comment"

class diagram
--------------------------attachment-content--

